[platformio]
src_dir = .
include_dir = .
default_envs = release

[env:release]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
extra_scripts = pre:scripts/build_script.py

; here you'll fill in the exact board and ldscript for your project
board = nucleo_c092rc
board_build.ldscript = STM32C092XX_FLASH.ld

build_flags = 
    -std=gnu23
    -DUSE_HAL_DRIVER
    -DSTM32C092xx ; with disco_f334c8 only
    -ICore/Inc
    -IDrivers/CMSIS/Include/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/
    -IDrivers/STM32C0xx_HAL_Driver/Inc/Legacy/
    -IDrivers/CMSIS/Device/ST/STM32C0xx/Include/

build_src_filter =
    +<Core/Src/>
    +<Drivers/STM32C0xx_HAL_Driver/Src/>
    -<Drivers/STM32C0xx_HAL_Driver/Src/*_template.c>
    +<./startup_stm32c092xx.s>

; here you will add other folders. To do that correctly go check other
; repo where it's already done, or check the generated Makefile

; here you will add libraries you need (e.g. libeagletrt, libring-buffer, ...)
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0

check_tool = clangtidy
check_flags =
    clangtidy: --checks=-*,cert-*,clang-analyzer-*,bugprone-*,performance-*,readability-*,-bugprone-easily-swappable-parameter
    clangtidy: --warnings-as-errors=clang-analyzer-*,bugprone-*
    clangtidy: --header-filter=^.*Core/(Inc|Src)/.+/[^/]+\.(c|h)$
    clangtidy: --system-headers=false
check_src_filters =
    -<**>
    # +<Core/Src/subfolder> ; CHANGE TO YOUR SUBFOLDER
    # +<Core/Inc/subfolder> ; CHANGE TO YOUR SUBFOLDER

[env:tests]
platform = native
test_framework = unity
test_build_src = true
build_flags =
    -DEAGLETRT_STATIC=
    -DEAGLETRT_STATIC_INLINE=
; fill in other required includes
build_src_filter =
; here you will add other folders where your modules are
lib_deps =
    https://github.com/eagletrt/libeagletrt-sw#v0.1.0

[env:bootloader]
platform = ststm32
upload_protocol = stlink
debug_tool = stlink
platform_packages = 
  toolchain-gccarmnoneeabi@=1.140201.0
monitor_speed = 115200
extra_scripts = pre:scripts/build_script.py

; here you'll fill in the exact board and ldscript for your project
board = 
board_build.ldscript = 

build_flags =
    -std=gnu23
    -DUSE_HAL_DRIVER

build_src_filter =
    +<*-bootloader-sw/Core/Src/>
; here you will add other folders. To do that correctly go check other
; repo where it's already done, or check the generated Makefile
